---

- name: Install PHP packages
  run_once: true
  apt: name={{ item }} state=present
  with_items:
      - php7.1
      - php7.1-cli
      - php7.1-curl
      - php7.1-gd
      - php7.1-fpm
      - php7.1-pspell
      - php7.1-tidy
      - php7.1-imagick
      - php7.1-mbstring
      - php7.1-dev
      - php7.1-xml
      - php7.1-xmlrpc
      - php7.1-xmlreader
      - php7.1-xmlwriter
      - php7.1-mysql
      - php7.1-cgi

# - name: Do fpm/php.ini
#   template: src=etc/php5/fpm/php.ini dest=/etc/php5/fpm/php.ini owner=root group=root mode=0644
#   notify: php5-fpm restart
